#!/usr/bin/env bash
# Bundles all scripts into a single self-contained dist/setup-bundled.sh
# suitable for: curl -fsSL <url> | sudo bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST="${REPO_ROOT}/dist"
OUT="${DIST}/setup-bundled.sh"

mkdir -p "$DIST"

# Helper: strip shebang from a file
strip_shebang() { grep -v '^#!/' "$1"; }

{
    cat <<'HEADER'
#!/usr/bin/env bash
# hypervisors setup — bundled single-file version
# Do not edit this file directly; edit the source files and run build.sh.
set -euo pipefail
HEADER

    echo "# Built: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    # -----------------------------------------------------------------------
    # Embed lib/utils.sh (without resolve_config — replaced below)
    # -----------------------------------------------------------------------
    echo "# === lib/utils.sh ==="
    strip_shebang "${REPO_ROOT}/lib/utils.sh" \
        | grep -v '^# ---------------------------------------------------------------------------$' \
        | grep -v '^# Host config resolution'
    echo ""

    # -----------------------------------------------------------------------
    # Embed host configs as a case-based load_host_config() function
    # -----------------------------------------------------------------------
    echo "# === host configs ==="
    cat <<'HOST_FUNC_START'
load_host_config() {
    local hostname="$1"
    case "$hostname" in
HOST_FUNC_START

    for host_file in "${REPO_ROOT}"/hosts/*.sh; do
        local_base="$(basename "$host_file" .sh)"
        [[ "$local_base" == "defaults" ]] && continue
        printf '        %s)\n' "$local_base"
        strip_shebang "${REPO_ROOT}/hosts/defaults.sh" | sed 's/^/            /'
        strip_shebang "$host_file" | sed 's/^/            /'
        printf '            ;;\n'
    done

    cat <<'HOST_FUNC_END'
        *)
            echo "[ERROR]   No config found for host: ${hostname}" >&2
            echo "          Known hosts: $(echo KNOWN_HOSTS | tr ' ' '\n' | grep -v '^$' | tr '\n' ' ')" >&2
            exit 1 ;;
    esac
}
HOST_FUNC_END

    # Patch in the actual known host names
    known=""
    for host_file in "${REPO_ROOT}"/hosts/*.sh; do
        base="$(basename "$host_file" .sh)"
        [[ "$base" == "defaults" ]] && continue
        known="$known $base"
    done
    # Replace the KNOWN_HOSTS placeholder in the output so far
    # (sed on the accumulated output isn't possible here; we write a wrapper instead)
    echo ""

    # resolve_config for bundled mode — calls load_host_config instead of sourcing files
    cat <<RESOLVE_FUNC
resolve_config() {
    local config_arg="\${1:-}"
    local hostname

    if [[ -n "\$config_arg" ]]; then
        hostname="\$config_arg"
    else
        hostname="\$(hostname -f)"
        [[ "\$hostname" == *.* ]] || hostname="\${hostname}.local"
    fi

    load_host_config "\$hostname"
    log_info "Loaded config for: \${hostname}"
}
RESOLVE_FUNC
    echo ""

    # -----------------------------------------------------------------------
    # Embed each task as a function
    # -----------------------------------------------------------------------
    for task_file in \
        "${REPO_ROOT}/tasks/packages.sh" \
        "${REPO_ROOT}/tasks/gpu.sh" \
        "${REPO_ROOT}/tasks/network.sh" \
        "${REPO_ROOT}/tasks/storage.sh" \
        "${REPO_ROOT}/tasks/zpool.sh" \
        "${REPO_ROOT}/tasks/system.sh" \
        "${REPO_ROOT}/tasks/wakelet.sh" \
        "${REPO_ROOT}/tasks/vm-builder-agent.sh"; do

        task_name="$(basename "$task_file" .sh | tr '-' '_')"
        echo "# === tasks/$(basename "$task_file") ==="
        echo "task_${task_name}() {"
        strip_shebang "$task_file"
        echo "}"
        echo ""
    done

    # -----------------------------------------------------------------------
    # Main orchestration body (inline — avoids fragile sed transforms on setup.sh)
    # -----------------------------------------------------------------------
    cat <<'MAIN'
# === main ===
CONFIG_HOST=""

usage() {
    cat <<EOF
Usage: sudo bash setup-bundled.sh [--config <hostname>]

Options:
  --config <hostname>   Use config for this hostname (default: auto-detect via hostname -f)
  --help                Show this help message
EOF
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --config) CONFIG_HOST="$2"; shift 2 ;;
        --help|-h) usage ;;
        *) die "Unknown argument: $1. Run with --help for usage." ;;
    esac
done

require_root
check_ubuntu_version
resolve_config "$CONFIG_HOST"

if [[ "$VM_BUILDER_AGENT_ENABLED" == true && -z "${VM_BUILDER_AGENT_TRUSTED_CA_URL:-}" ]]; then
    die "VM_BUILDER_AGENT_TRUSTED_CA_URL must be set when VM_BUILDER_AGENT_ENABLED=true"
fi

log_info "=== Starting hypervisor setup for $(hostname) ==="

task_packages
task_gpu
task_network
task_storage
[[ "$ZPOOL_ENABLED" == true ]] && task_zpool
task_system

[[ "$WAKELET_ENABLED" == true ]] && task_wakelet
[[ "$VM_BUILDER_AGENT_ENABLED" == true ]] && task_vm_builder_agent

if [[ "$REBOOT_REQUIRED" == true ]]; then
    echo ""
    log_info "=== REBOOT REQUIRED ==="
    log_info "The following changes require a reboot to take effect:"
    printf '%b' "$REBOOT_REASON"
    echo ""
    log_info "Please reboot and re-run setup to verify all settings."
    log_info "  sudo reboot"
    exit 1
fi

echo ""
log_info "=== Setup complete. No reboot required. ==="
MAIN

} > "$OUT"

chmod +x "$OUT"

# Syntax check before reporting success
bash -n "$OUT"

size="$(wc -c < "$OUT")"
lines="$(wc -l < "$OUT")"
echo "Built: ${OUT} (${size} bytes, ${lines} lines)"
echo ""
echo "Usage:"
echo "  # Run directly:"
echo "  sudo bash ${OUT}"
echo ""
echo "  # Or after publishing to GitHub Releases:"
echo "  curl -fsSL https://github.com/tlhakhan/hypervisors/releases/latest/download/setup-bundled.sh | sudo bash"
echo "  curl -fsSL https://github.com/tlhakhan/hypervisors/releases/latest/download/setup-bundled.sh | sudo bash -s -- --config nvidia-1.local"
